# Name your project! Project names should be lowercase and use underscores as separators
# See documentation: https://docs.getdbt.com/docs/build/projects

name: 'test_midas'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'test_midas'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/build/projects

models:
  test_midas:
    # Config indicated by + and applies to all files under models/
    staging:
      materialized: table
      +schema: payments_v1
    # Marts/fact tables
    +materialized: table
    +schema: payments_v1